services:
    custom-postgres:
        container_name: pathless-database
        env_file: ../.env
        build:
            context: ..
            dockerfile: deploy/Dockerfile.db
        ports:
            - '${POSTGRES_PORT}:5432'

    custom-node:
        container_name: pathless-server
        env_file: ../.env
        build:
            context: ..
            dockerfile: deploy/Dockerfile.server
        ports:
            - '${PORT}:1000'
        depends_on:
            - custom-postgres
